# Generated by Django 3.1.4 on 2020-12-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=45)),
                ('fund_name', models.CharField(max_length=45)),
            ],
        ),
    ]
