# Generated by Django 3.1.4 on 2021-01-06 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20210106_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_db',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='card_db',
            name='create_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='exhibition_db',
            name='finish_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='exhibition_db',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
