# Generated by Django 3.1.4 on 2021-01-06 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_organization_exhibition_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_stor', models.CharField(max_length=45)),
                ('off_stor', models.CharField(max_length=45)),
                ('trans_ex', models.CharField(max_length=45)),
                ('return_ex', models.CharField(max_length=45)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.author_db')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.card_db')),
                ('exhibition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.exhibition_db')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.organization')),
            ],
        ),
    ]
