# Generated by Django 3.1.4 on 2021-01-06 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='add_stor',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='control',
            name='off_stor',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='control',
            name='return_ex',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='control',
            name='trans_ex',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
